using System;
using System.Data;
using System.Windows.Forms;

namespace QLTN
{
    public partial class frmKhoa : Form
    {
        public frmKhoa()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
        }

        private void frmKhoa_Load(object sender, EventArgs e)
        {
        }
    }
}
